---

driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-15.04
  - name: debian-8.7
  - name: debian-8.6

verifier:
  name: inspec

suites:
  - name: default-12
    run_list:
      - recipe[devopsdance-dnsmasq::_test]
    provisioner:
      require_chef_omnibus: 12
  - name: default-13
    run_list:
      - recipe[devopsdance-dnsmasq::_test]
    provisioner:
      require_chef_omnibus: 13
