---

driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.19.36-1

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[devopsdance-dnsmasq::_test]
