name 'devopsdance-dnsmasq'
maintainer 'DevopsDance'
maintainer_email 'team@devops.dance'
license 'Apache-2.0'
description 'Installs and configures DNSMasq'
version '3.0.0'
source_url 'https://github.com/DevopsDance/chef-cookbook-dnsmasq'
issues_url 'https://github.com/DevopsDance/chef-cookbook-dnsmasq/issues'
chef_version '~> 12'

depends 'ubuntu'
depends 'debian'
depends 'chef-sugar'

supports 'ubuntu', '>= 15.04'
supports 'debian', '>= 7.0'
